// MultiCamCpp.H - MULTICAM C++ API
// Do not edit this file

#if !defined(__MULTICAMCPP_H__)
#define __MULTICAMCPP_H__

#include <iostream>
#include "multicam.h"

#include "MultiCamCppExternal.h"
#include "MultiCamCppInternal.h"

#endif
